# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b98951f5e0fe18fae796d4afce365a2b529e163ea7652637c5eb9d06f613ca3ebf51f8d61c1595355b0f2d7ff978af38b07a26eee11bcc28768f12a9eacf92a

test:
  secret_key_base: 7d532d01c6906b1d929ab8ab00ece815b8176513e601f7967bbe25cb4606eb6f8521eb433e2df448f0b5bb022a0d9220ad38af5715fe46e58451a689322f28f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
